server:
  port: 9191


spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296
    gateway:
      routes:
        - id: WORKFLOW-SERVICE
          uri: lb://WORKFLOW-SERVICE
          predicates:
            - Path=/workflow/**
          filters:
            - name: CircuitBreaker
              args:
                name: WORKFLOW-SERVICE
                fallbackuri: forward:/workflowServiceFallBack


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost



hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

